#!/bin/bash
set -ex

# DockerHub Automated Build를 위한 Custom Environment Hook
# 빌드 시에 사용자 환경변수를 전달한다

docker build \
    --build-arg BROKER="${BROKER}" \
    -f $DOCKERFILE_PATH \
    -t $IMAGE_NAME .
